name: GoTyping CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    uses: Joao-Tiago-Almeida/github-base-templates/.github/workflows/build.yml@v0.0.0
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      IMAGE_NAME: github-base-templates
      IMAGE_TAG: build-${{ github.sha }}-${{ github.event.repository.name }}

  tag:
    needs: build
    uses: Joao-Tiago-Almeida/github-base-templates/.github/workflows/tag.yml@v0.0.0
    with:
      OLD_IMAGE_NAME: github-base-templates
      OLD_IMAGE_TAG: build-${{ github.sha }}-${{ github.event.repository.name }}
      NEW_IMAGE_NAME: github-base-templates
      NEW_IMAGE_TAG: ${{ github.event.repository.name }}

    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
